# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1ddb32ee-9a4d-4fff-a012-30d0486bc8b6";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EE76-7E13";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home/janek/Data" =
    { device = "/dev/disk/by-uuid/181B32AD7C5F5F50";
      fsType = "ntfs-3g";
      # fsType = "ntfs3";
      options = [ "rw" "uid=1000" "gid=100"];
    };

  fileSystems."/home/janek/BigData" =
    { device = "/dev/disk/by-uuid/48A0439EA043917C";
      fsType = "ntfs-3g";
      # fsType = "ntfs3";
      # options = [ "rw" ];# "uid=1000"]; "uid=1000"];
      options = [ "rw" "uid=1000" "gid=100"];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0625a3ee-d7d5-47b6-8213-fd3cb5bb3cc2"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp16s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp19s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
